main: me.sjts98k.Main
name: SimpleAutoExec
version: 3.0
commands:
  addexec:
    description: "[SAE] Adds a command to execute"
    usage: /addexec <command to execute>
  reexec:
    description: "[SAE] Executes all commands"
    usage: /reexec
  delexec:
    description: "[SAE] Removes command from the file"
    usage: /delexec <command to remove/all>
  listexec:
    description: "[SAE] Shows all commands in the file"
    usage: /listexec
  flagexec:
    description: "[SAE] Give properties to commands"
    usage: /flagexec <command to flag> <flag>
  flagexeclist:
    description: "[SAE] Shows all available flags"
    usage: /flagexeclist
permissions:
  sae.addexec:
    default: op
  sae.reexec:
    default: op
  sae.delexec:
    default: op
  sae.listexec:
    default: op
  sae.flagexec:
    default: op
  sae.flagexec.list:
    default: op